name: Run Tests
on:
  - push
  - pull_request

env:
  GO_VERSION: "1.20"
  POSTGRES_DB: "test"
  POSTGRES_USER: "jeff"
  POSTGRES_PASSWORD: "secret"

jobs:
  unit:
    runs-on: ubuntu-latest
    name: Unit tests

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: test
          POSTGRES_USER: jeff
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout repo
        uses: actions/checkout@8ade135a41bc03ea155e62e844d188df1ea18608

      - uses: actions/setup-go@f111f3307d8850f501ac008e886eec1fd1932a34
        with:
          go-version: "${{env.GO_VERSION}}"

      - name: Run tests
        env:
          TEST_DATABASE_URL: postgresql://jeff:secret@localhost:5432/test?sslmode=disable
        run: |
          make test
