name: Run Tests
on:
- push
- pull_request

env:
  GO_VERSION: 1.18

jobs:
  unit:
    runs-on: ubuntu-latest
    name: Unit tests

    services:
      postgres:
        image: postgres:12
        env:
          POSTGRES_PASSWORD: secret
          POSTGRES_DB: test
          POSTGRES_USER: jeff
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: "Install Go ${{env.GO_VERSION}}"
      uses: actions/setup-go@v2
      with:
        go-version: "${{env.GO_VERSION}}"

    - name: Install Ginkgo CLI
      run: |
<<<<<<< HEAD
        go install github.com/onsi/ginkgo/ginkgo@v1.4
=======
        go install github.com/onsi/ginkgo/ginkgo@v1.6
>>>>>>> 67d9ba3 (upgrades go in gha and ginkgo)

    - name: Run tests
      env:
        TEST_DATABASE_URL: postgresql://jeff:secret@localhost:5432/test?sslmode=disable
      run: |
        ginkgo -r -nodes=4
